### ISSUE TITLE
ESRI Enterprise Add-On: Required updates for accelerator

### ISSUE THREAD

**Issue by jayhaddad** [Azure/missionlz#1068]
```[tasklist]
### Tasks
- [ ] Remove hardcoded URI
- [ ] Ensure PE are used
- [ ] Promote use of securestrings or keyvault
- [ ] ensure diagnostics settings are all set for deployed resources
- [ ] Integrate into tier3
- [ ] Remove dependencies on external files
```
